name: Jest tests pipeline
on: 
  pull_request:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules and run tests
        run: |
          cd projeto-kokama
          yarn
          yarn test
      - name: Run linters
        uses: wearerequired/lint-action@v1
        with:
          eslint_command_prefix: cd projeto-kokama
          eslint: true
